# Generated by Django 4.0.4 on 2022-08-27 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Cast', models.CharField(max_length=200)),
                ('Genre', models.CharField(max_length=200)),
                ('Year', models.CharField(max_length=200)),
                ('Language', models.CharField(max_length=200)),
                ('Booking', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MovieAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timings', models.CharField(max_length=100)),
                ('Location', models.DateField()),
                ('Price', models.IntegerField()),
                ('Theatrename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.movies')),
            ],
        ),
    ]
