# Generated by Django 4.0.4 on 2022-08-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Booking',
            field=models.DateField(),
        ),
    ]
