# Generated by Django 4.0.4 on 2022-08-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_rename_booking_movies_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='ReleaseDate',
            field=models.DateTimeField(),
        ),
    ]
