# Generated by Django 4.0.4 on 2022-08-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_alter_movies_releasedate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieavailable',
            options={'verbose_name': 'Movies Show List'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movie List'},
        ),
        migrations.AlterModelTable(
            name='movieavailable',
            table='Movies Show',
        ),
        migrations.AlterModelTable(
            name='movies',
            table='Movies',
        ),
    ]
